image: node:latest

stages:
- build-frontend
- deploy



build-frontend:
  type: build
  stage: build-frontend
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - echo "Building React.js App"
    - cd frontend
    - ls
    - npm install
    - npm run-script build 
    - ls build/
  artifacts:
    paths:
    - frontend/build/*
    - frontend/app-server/*

deploy:
  type: deploy
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - echo "Deploying React.js App"
    - ls
    - ls frontend
    - ls frontend/build
    - cp -R frontend/build frontend/app-server/react
    - ls frontend/app-server
    - ls frontend/app-server/build
    - cd frontend/app-server
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APPNAME_IN_HEROKU --api-key=$API_KEY_FOR_HEROKU_APP

  only:
    - master
    - release


#   when: manual