#######################################################################################
### REGISTRATION
#######################################################################################
POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "ADMIN",
    "lastName" : "ONE",
    "email" : "admin_one@email.com",
    "password" : "ADMIN_ONE"
}
###
POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "USER",
    "lastName" : "ONE",
    "email" : "userOne@email.com",
    "password" : "User_One"
}
###

POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "USER",
    "lastName" : "TWO",
    "email" : "userTwo@email.com",
    "password" : "User_Two"
}
###
POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "A",
    "lastName" : "a",
    "email" : "a@a.com",
    "password" : "aaaaaa"
}

###
POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "Sriram",
    "lastName" : "Ponangi",
    "email" : "sriram.ponangi@dal.ca",
    "password" : "0123456789"
}
#######################################################################################
### LOGIN
#######################################################################################


POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "userOne@email.com",
    "password" : "User_One"
}

###
POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "userTwo@email.com",
    "password" : "User_Two"
}

###
POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "a@a.com",
    "password" : "aaaaaa"
}

###
POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "admin_one@email.com",
    "password" : "ADMIN_ONE"
}


###
POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "sriram.ponangi@dal.ca",
    "password" : "0123456789"
}
#######################################################################################
### TEST GROUPS API
#######################################################################################
GET http://localhost:4000/api/groups/user/all
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRjNjQ5OTE2ZWMxZDQzNzg4NzYiLCJyb2xlIjoiQURNSU4iLCJmaXJzdE5hbWUiOiJBRE1JTiIsImxhc3ROYW1lIjoiT05FIiwiZW1haWwiOiJhZG1pbl9vbmVAZW1haWwuY29tIiwiaWF0IjoxNjE0OTU2MTY5LCJleHAiOjE2MTQ5NTk3MDl9.44duvig69kVZ9EVa9QJwC9bvhK3rC96DX9RjL_n0TgI

###
POST http://localhost:4000/api/groups/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRkNjQ5OTE2ZWMxZDQzNzg4N2EiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlNyaXJhbSIsImxhc3ROYW1lIjoiUG9uYW5naSIsImVtYWlsIjoic3JpcmFtLnBvbmFuZ2lAZGFsLmNhIiwiaWF0IjoxNjE0OTU3MzU1LCJleHAiOjE2MTQ5NjA4OTV9.FeM8n0NSEYRRexHbo2q-4s13cFFmzheeupL31o3Khr8

{
    "name" : "GROUP-ONE",
    "description" : "Description of Group One is written here...",
    "location_country" : "Canada",
    "location_name" : "Halifax, Nova Scotia",
    "highlight" : "Cycling"
}
###
POST http://localhost:4000/api/groups/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRjNjQ5OTE2ZWMxZDQzNzg4NzYiLCJyb2xlIjoiQURNSU4iLCJmaXJzdE5hbWUiOiJBRE1JTiIsImxhc3ROYW1lIjoiT05FIiwiZW1haWwiOiJhZG1pbl9vbmVAZW1haWwuY29tIiwiaWF0IjoxNjE0OTU2MTY5LCJleHAiOjE2MTQ5NTk3MDl9.44duvig69kVZ9EVa9QJwC9bvhK3rC96DX9RjL_n0TgI

{
    "name" : "GROUP-TWO",
    "description" : "Description of Group Two is written here...",
    "location_country" : "Canada",
    "location_name" : "Halifax, Nova Scotia",
    "highlight" : "Cycling"
}

###
POST http://localhost:4000/api/groups/members
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRjNjQ5OTE2ZWMxZDQzNzg4NzYiLCJyb2xlIjoiQURNSU4iLCJmaXJzdE5hbWUiOiJBRE1JTiIsImxhc3ROYW1lIjoiT05FIiwiZW1haWwiOiJhZG1pbl9vbmVAZW1haWwuY29tIiwiaWF0IjoxNjE0OTU2MTY5LCJleHAiOjE2MTQ5NTk3MDl9.44duvig69kVZ9EVa9QJwC9bvhK3rC96DX9RjL_n0TgI

{
    "name" : "GROUP-ONE",
    "location_country" : "Canada",
    "location_name" : "Halifax, Nova Scotia",
    "highlight" : "Cycling"
}
###
GET http://localhost:4000/api/groups/members
?name=GROUP-ONE
&location_country=Canada
&location_name=Halifax, Nova Scotia
&highlight=Cycling
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRjNjQ5OTE2ZWMxZDQzNzg4NzYiLCJyb2xlIjoiQURNSU4iLCJmaXJzdE5hbWUiOiJBRE1JTiIsImxhc3ROYW1lIjoiT05FIiwiZW1haWwiOiJhZG1pbl9vbmVAZW1haWwuY29tIiwiaWF0IjoxNjE0OTU2MTY5LCJleHAiOjE2MTQ5NTk3MDl9.44duvig69kVZ9EVa9QJwC9bvhK3rC96DX9RjL_n0TgI

###

POST http://localhost:4000/api/groups/member
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRkNjQ5OTE2ZWMxZDQzNzg4N2EiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlNyaXJhbSIsImxhc3ROYW1lIjoiUG9uYW5naSIsImVtYWlsIjoic3JpcmFtLnBvbmFuZ2lAZGFsLmNhIiwiaWF0IjoxNjE0OTU3MzU1LCJleHAiOjE2MTQ5NjA4OTV9.FeM8n0NSEYRRexHbo2q-4s13cFFmzheeupL31o3Khr8

{
    "name" : "GROUP-ONE",
    "location_country" : "Canada",
    "location_name" : "Halifax, Nova Scotia",
    "highlight" : "Cycling"
}

###
POST http://localhost:4000/api/groups/member
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyNDRkMjQ5OTE2ZWMxZDQzNzg4NzkiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IkEiLCJsYXN0TmFtZSI6ImEiLCJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MTQ5NTYyMjUsImV4cCI6MTYxNDk1OTc2NX0.BX5_6Wkjd17qMlH7Lz4z7YsH5oZcsMuftj6WXFpAso4

{
    "name" : "GROUP-TWO",
    "location_country" : "Canada",
    "location_name" : "Halifax, Nova Scotia",
    "highlight" : "Cycling"
}
#######################################################################################
### TEST USER API
#######################################################################################

###
GET http://localhost:4000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyMzI0N2Y0N2I3YTczOGM0ZDI3ZjAiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlNyaXJhbSIsImxhc3ROYW1lIjoiUG9uYW5naSIsImVtYWlsIjoic3JpcmFtNTc5NUBnbWFpbC5jb20iLCJpYXQiOjE2MTQ5NTE2MzgsImV4cCI6MTYxNDk1NTE3OH0.k-RnG0loLIoaA8_M4QdCyxMvRSQYjtpfgJkblOo5iho


###
POST http://localhost:4000/api/user/forgot-password
content-type: application/json

{

    "email" : "sriram.ponangi@dal.ca"
}


###
POST http://localhost:4000/api/user/update-profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQxMWZiMzI5ZmUxNGM1MDRmNDg2NzUiLCJyb2xlIjoiQURNSU4iLCJmaXJzdE5hbWUiOiJBRE1JTiIsImxhc3ROYW1lIjoiT05FIiwiZW1haWwiOiJhZG1pbl9vbmVAZW1haWwuY29tIiwiaWF0IjoxNjE0ODk4ODM4LCJleHAiOjE2MTQ5MDIzNzh9.ioUkZAnhpdeROzVyabCqkw9GnFw1MRe51N7H3c2fdsc

{
    "firstName": "ADMIN",
    "lastName": "One",
    "password": "123456789",
    "confirmPassword": "123456789"
}