POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "One",
    "lastName" : "User",
    "email" : "userOne@email.com",
    "password" : "User_One"
}
###

POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "Two",
    "lastName" : "User",
    "email" : "userTwo@email.com",
    "password" : "User_Two"
}
###
POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "firstName" : "A",
    "lastName" : "a",
    "email" : "a@a.com",
    "password" : "aaaaaa"
}
###
POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "userOne@email.com",
    "password" : "User_One"
}

###

POST http://localhost:4000/api/auth/login
content-type: application/json

{

    "email" : "userTwo@email.com",
    "password" : "User_Two"
}

###
GET http://localhost:4000/api/groups/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDI2MGQxOTA2OGU4ODQzNzQ4ZmFiZDYiLCJpYXQiOjE2MTMzMzEwNjksImV4cCI6MTYxMzMzNDYwOX0.UzzPeq8Uy-PN8PDaOss33Yo0pYn3trXzLuhEEimZWcc



###
GET http://localhost:4000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDI2MGQxOTA2OGU4ODQzNzQ4ZmFiZDYiLCJpYXQiOjE2MTMzMzg1ODksImV4cCI6MTYxMzM0MjEyOX0.h0jZ1HxfwVrPxbOv83PG18o3g2xhB0ubCOXciDWTZsk


###
GET http://localhost:4000/api/groups/all