######################################################################################################
### REGISTER
######################################################################################################

POST https://csci-5709-backend.herokuapp.com/api/auth/register
content-type: application/json

{
    "firstName" : "One",
    "lastName" : "User",
    "email" : "userOne@email.com",
    "password" : "User_One"
}
###

POST https://csci-5709-backend.herokuapp.com/api/auth/register
content-type: application/json

{
    "firstName" : "Two",
    "lastName" : "User",
    "email" : "userTwo@email.com",
    "password" : "User_Two"
}
###
POST https://csci-5709-backend.herokuapp.com/api/auth/register
content-type: application/json

{
    "firstName" : "A",
    "lastName" : "a",
    "email" : "a@a.com",
    "password" : "aaaaaa"
}
###
POST https://csci-5709-backend.herokuapp.com/api/auth/register
content-type: application/json

{
    "firstName" : "Sriram",
    "lastName" : "Ponangi",
    "email" : "sriram.ponangi@dal.ca",
    "password" : "123456789"
}


######################################################################################################
### LOGIN
######################################################################################################

###
POST https://csci-5709-backend.herokuapp.com/api/auth/login
content-type: application/json
{

    "email" : "userOne@email.com",
    "password" : "User_One"
}

###

POST https://csci-5709-backend.herokuapp.com/api/auth/login
content-type: application/json

{

    "email" : "userTwo@email.com",
    "password" : "User_Two"
}

###
GET https://csci-5709-backend.herokuapp.com/api/groups/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDI2MGQxOTA2OGU4ODQzNzQ4ZmFiZDYiLCJpYXQiOjE2MTM3OTczMTEsImV4cCI6MTYxMzgwMDg1MX0.qgNbPiLsjpfkRPOgzNjBFLdJXMgE0kxq4Yu65t4ysoE



###
GET https://csci-5709-backend.herokuapp.com/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDI2MGQxOTA2OGU4ODQzNzQ4ZmFiZDYiLCJpYXQiOjE2MTM3OTczMTEsImV4cCI6MTYxMzgwMDg1MX0.qgNbPiLsjpfkRPOgzNjBFLdJXMgE0kxq4Yu65t4ysoE


###
GET https://csci-5709-backend.herokuapp.com/api/groups/all

