
#####################################
### CREATE COMMENT IN GROUP
#####################################
###

POST http://localhost:4000/api/group/comment
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "groupId" : "604a7bfc7d497d9bc813b607",
    "text": "Hello, World! Typical Third Comment..."
}


###

POST http://localhost:4000/api/group/comment
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "groupId" : "604a7bfc7d497d9bc813b607",
    "text": "Hello, World! Typical Second Comment. "
}
#####################################
### GET COMMENTS IN GROUP
#####################################


#* Authors: 
##    - Rajni, Puni

###

GET http://localhost:4000/api/group/comment
?groupId=604a7bfc7d497d9bc813b607
content-type: application/json
Authorization: Bearer <Valid JWT Token>

