
#####################################
### JOIN GROUP
#####################################


###

POST http://localhost:4000/api/group/member
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "name" : "fishing Waterfront",
    "highlightId" : "60568c3f5b693541706b93e7"
}

###

POST http://localhost:4000/api/group/member
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "name" : "fishing Peggy's Cove",
    "highlightId" : "60568c3f5b693541706b93e8"
}


###

POST http://localhost:4000/api/group/member
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "name" : "fishing Waterfront",
    "highlightId" : "60568c3f5b693541706b93e6"
}

###
POST http://localhost:4000/api/group/member
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "name" : "Jogging Group",
    "highlightId" : "604a755cddad4af1482a1ad1"
}

#####################################
### LEAVE GROUP
#####################################
###

DELETE http://localhost:4000/api/group/member
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "_id" : "606745956a2514c4b425da0f"
}

###
DELETE http://localhost:4000/api/group/member
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "name" : "Jogging Group",
    "highlightId" : "604a755cddad4af1482a1ad1"
}

#####################################
### GET GROUP MEMBERS
#####################################

###
GET http://localhost:4000/api/group/member
?group_id=60674c305ba247ef3003b04c
content-type: application/json
Authorization: Bearer <Valid JWT Token>


