
#####################################
### CREATE COMMENT IN GROUP
#####################################
###

POST http://localhost:4000/api/group/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDRhNjI5OTUzNDk0ZWYyYTRiZjk3YmEiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlNyaVJhbSIsImxhc3ROYW1lIjoiUG9uYW5naSIsImVtYWlsIjoidXNlck9uZUBlbWFpbC5jb20iLCJpYXQiOjE2MTU5MDkxMTgsImV4cCI6MTYxNTkxMjY1OH0.H6_lLEKLwlYw1t6MiAzLo31A4gomw9dRo4cenEIUgwY

{
    "groupId" : "604a7bfc7d497d9bc813b607",
    "text": "Hello, World! Typical Third Comment..."
}


###

POST http://localhost:4000/api/group/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDRhNjI5OTUzNDk0ZWYyYTRiZjk3YmEiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlNyaVJhbSIsImxhc3ROYW1lIjoiUG9uYW5naSIsImVtYWlsIjoidXNlck9uZUBlbWFpbC5jb20iLCJpYXQiOjE2MTU4Njc0NDEsImV4cCI6MTYxNTg3MDk4MX0.7DExJjE4Pa9ae8E_jjFg_x0bsuWjTWglKW3Jksknunw

{
    "groupId" : "604a7bfc7d497d9bc813b607",
    "text": "Hello, World! Typical Second Comment. "
}
#####################################
### GET COMMENTS IN GROUP
#####################################


#* Authors: 
##    - Rajni, Puni

###

GET http://localhost:4000/api/group/comment
?groupId=604a7bfc7d497d9bc813b607
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDRhNjI5OTUzNDk0ZWYyYTRiZjk3YmEiLCJyb2xlIjoiVVNFUiIsImZpcnN0TmFtZSI6IlNyaVJhbSIsImxhc3ROYW1lIjoiUG9uYW5naSIsImVtYWlsIjoidXNlck9uZUBlbWFpbC5jb20iLCJpYXQiOjE2MTU5NTUyNzUsImV4cCI6MTYxNTk1ODgxNX0.XPQylICgzb4mscqUrkLoS9MsfZ6Nf51yukz8lAbFpfQ

