
#######################################################################################
### USER APIs
#######################################################################################


### Get Basic Info of the logged-in user
GET http://localhost:4000/api/user/
Authorization: Bearer <Valid JWT Token>

### MyGroups - Get the basic info of all the groups the logged-in user is part of.
GET http://localhost:4000/api/user/groups
Authorization: Bearer <Valid JWT Token>

###
POST http://localhost:4000/api/user/forgot-password
content-type: application/json

{
    "email" : "sriram.ponangi@dal.ca"
}

###
POST http://localhost:4000/api/user/update-profile
content-type: application/json
Authorization: Bearer <Valid JWT Token>

{
    "firstName": "SriRam",
    "lastName": "Ponangi",
    "password": "0123456789",
    "confirmPassword": "0123456789"
}